COLLECTION_TO_URL = {
    'arg': 'http://scielo.org.ar/oai/scielo-oai.php',
    'bol': 'http://www.scielo.org.bo/oai/scielo-oai.php',
    'nbr': '',
    'scl': 'https://www.scielo.br/oai/scielo-oai.php',
    'chl': '',
    'col': 'http://www.scielo.org.co/oai/scielo-oai.php',
    'cri': 'https://www.scielo.sa.cr/oai/scielo-oai.php',
    'cub': 'http://scielo.sld.cu/oai/scielo-oai.php',
    'ecu': 'http://scielo.senescyt.gob.ec/oai/scielo-oai.php',
    'esp': 'https://scielo.isciii.es/oai/scielo-oai.php',
    'mex': 'http://scielo.org.mx/oai/scielo-oai.php',
    'pry': 'http://scielo.iics.una.py/oai/scielo-oai.php',
    'psi': 'http://pepsic.bvsalud.org/oai/scielo-oai.php',
    'per': 'http://www.scielo.org.pe/oai/scielo-oai.php',
    'prt': 'http://www.scielo.mec.pt/oai/scielo-oai.php',
    'pre': 'https://preprints.scielo.org/index.php/scielo/oai',
    'ssp': '',
    'rve': 'http://www.revenf.bvs.br/oai/scielo-oai.php',
    'sss': 'http://socialsciences.scielo.org/oai/scielo-oai.php',
    'sza': 'http://www.scielo.org.za/oai/scielo-oai.php',
    'ury': 'http://www.scielo.edu.uy/oai/scielo-oai.php',
    'ven': 'http://ve.scielo.org/oai/scielo-oai.php',
    'wid': 'https://westindies.scielo.org/oai/scielo-oai.php'
}
